str1=str.upper("rohit ")
print(str1)
str2=str.lower("sakhare")
print(str2)
str3=str.title("welcome to sunbeam")
print(str3)
str4=str.capitalize("welcome to sunbeam")
print(str4)
str5=str.swapcase("Hi Guys My Name Is Rohit ")
print(str5)